package common;

public enum MessageType {
	TravlerGUILogin, TravlerAddNew,TravlerLogOut,TravlerLogOutALL,TravlerIsConnected ,TravelerDashboardReservations, TravelerDashboardWaitingList,
	TravelerDashboardShowUserDetails, TravelerDashboardCancelReservation, 
	TravelerDashboardExitWaitingList, TravelerDashboardChangeEmail, 
	TravlerDashboardChangePhoneNumber, TravelerVisitReservationScreenUpdateDetails, 
	TravelerVisitReservationCreateReservation, TravelerVisitReservationJoinWaitingList, 
	WorkerLogin, ApprovalScreenShowReservationDetailsAfterChoosingReservation, 
	ApprovalScreenChooseReservationOptions, ApprovalScreenUpdateStatusOfReservation,
	ParkManagerDashboardShowDetails, ParkManagerDashboardShowDetailsAfterChoosingPark,
	ParkManagerDashboardRequestVisitorChange, ParkManagerDashboardRequestQuotaInParkChange,
	ParkManagerDashboardRequestVisitTimeInMinutesChange, ParkManagerDashboardCreateReport,ParkManagerDashboardGetAllReportsForPark,
	ParkManagerDahsboardPreviewReport, WorkerDashboardShowDetails, 
	WorkerDashboardShowDetailsAfterChoosingPark, WorkerDashboardMakeAReservation,
	WorkerDashboardPaymentOnReservation, WorkerDashboardEnterPark, WorkerDashboardExitPark,
	ServiceDashboardShowDetails, 
	ServiceDashboardRegisterAGuide, DivisionManagerDashboardShowDetails,DivisionManagerDashboardAcceptRequest, DivisionManagerDashboardDenyRequest,DivisionManagerDashboardCreateReport,
	DivisionManagerChoosePark, DivisionManagerChangeStatusOfRequest, DivisionManagerViewReport,GetAllReportsDivisionManager,
	NotificationScreenShowMessage, NewClientConnected, ClientDisconnected, GuideLoginScreenLogin, CloseClient,
	ApprovalScreenApproveVisit, ApprovalScreenCancelVisit, GetAllReservations,GetAllReservationsParkManagerDashboard, AlternativeDateScreenCreateVisit, 
	SummaryPageUpdateEmailANdPhoneNumber;
}
